version: '3'
services:
  db:
    image: mysql:5.7.18
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:3.2.9
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  web: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - /myapp/node_modules
      - bundle:/bundle
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  spring:
    <<: *app_base
    command: "bundle exec spring server"
    ports: []
    tty: false
    stdin_open: false
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local

